a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = int(input())

print(a + b + c + d + e)
print((a + c) - (b * d))
print('{:.3f}'.format(a/b)) 
print(a**(c + b))
print('{:.3f}'.format(a/c)) 
print(a//c)
print(a%c)
print((a + b)//c)
print('{:.3f}'.format((a/c) - (b*e)))
print(a**b-c**b)
print((a**b)**c)
print(b*e)
print(b*b*e)
print(b*b*b*e)
print(b*b*b*b*e)
print(b*b*b*b*b*e)
print(b*b*b*b*b*b*e)
print(b*b*b*b*b*b*b*e)
print(b*b*b*b*b*b*b*b*e)
print(b*b*b*b*b*b*b*b*b*e)
print(b*b*b*b*b*b*b*b*b*b*e)
