a = input()
b = input()
c = input()
d = input()
e = input()

a = ( a =='True')
b = ( b =='True')
c = ( c =='True')
d = ( d =='True')
e = ( e =='True')

print (not a)
print (a and c)
print (a and b)
print (d and b)
print ((b and d) or e)
print (not(a and b))
print (not b and c)
print (not(b and c))
print (not a and not c)
print (e and not(a and b and c and d))
print (not(a and b and c and d) and(e or b))
